// layout.cpp — implementation of commander‑damage button layouts
#include "layout.h"
#include "ui/ui.h" /* generated by EEZ Studio, for objects.*  */

/* ---------------------------------------------------------
 * Rect helper
 * --------------------------------------------------------*/
typedef struct
{
    uint16_t x; /* left   */
    uint16_t y; /* top    */
    uint16_t w; /* width  */
    uint16_t h; /* height */
} rect_t;

/* ---------------------------------------------------------
 * Hard‑coded rectangles
 * --------------------------------------------------------*/
static const rect_t layout2[6] = {
    {10, 7, 100, 150}, // btn 0
    {130, 7, 100, 150} // btn 1
};

static const rect_t layout3[6] = {
    {10, 7, 89, 150},  // btn 0
    {107, 7, 123, 70}, // btn 1
    {107, 87, 123, 70} // btn 2
};

static const rect_t layout4[6] = {
    {10, 7, 100, 70},  // btn 0
    {130, 7, 100, 70}, // btn 1
    {10, 82, 100, 70}, // btn 2
    {130, 82, 100, 70} // btn 3
};

static const rect_t layout5[6] = {
    {10, 7, 70, 70},  // btn 0
    {86, 7, 70, 70},  // btn 1
    {10, 82, 70, 70}, // btn 2
    {86, 82, 70, 70}, // btn 3
    {163, 7, 70, 145} // btn 4
};

static const rect_t layout6[6] = {
    {10, 7, 70, 70},  // btn 0
    {86, 7, 70, 70},  // btn 1
    {163, 7, 70, 70}, // btn 2
    {10, 82, 70, 70}, // btn 3
    {86, 82, 70, 70}, // btn 4
    {163, 82, 70, 70} // btn 5
};

/* ---------------------------------------------------------
 * Global array of commander‑damage buttons
 * --------------------------------------------------------*/
lv_obj_t *cmd_btn[6];

/* ---------------------------------------------------------
 * Global array of commander‑damage buttons labels
 * --------------------------------------------------------*/
lv_obj_t *cmd_btn_label[6];

/* ---------------------------------------------------------
 * Apply layout to up to six buttons.
 * --------------------------------------------------------*/
void layout_commander_buttons(uint8_t count)
{
    const rect_t *table = NULL;
    switch (count)
    {
    case 2:
        table = layout2;
        break;
    case 3:
        table = layout3;
        break;
    case 4:
        table = layout4;
        break;
    case 5:
        table = layout5;
        break;
    case 6:
        table = layout6;
        break;
    default:
        return; /* unsupported */
    }

    for (uint8_t i = 0; i < 6; ++i)
    {
        if (i < count)
        {
            const rect_t *r = &table[i];
            lv_obj_clear_flag(cmd_btn[i], LV_OBJ_FLAG_HIDDEN);
            lv_obj_set_pos(cmd_btn[i], r->x, r->y);
            lv_obj_set_size(cmd_btn[i], r->w, r->h);
        }
        else if (cmd_btn[i])
        {
            lv_obj_add_flag(cmd_btn[i], LV_OBJ_FLAG_HIDDEN);
        }
    }
}

/* ---------------------------------------------------------
 * UI screen initialiser — map buttons and set default layout
 * --------------------------------------------------------*/
void single_lifecount_edh_layout_init(void)
{
    /* buttons generated by EEZ Studio (ui.h → objects.*) */
    cmd_btn[0] = objects.single_lifecount_edh_btn1;
    cmd_btn[1] = objects.single_lifecount_edh_btn2;
    cmd_btn[2] = objects.single_lifecount_edh_btn3;
    cmd_btn[3] = objects.single_lifecount_edh_btn4;
    cmd_btn[4] = objects.single_lifecount_edh_btn5;
    cmd_btn[5] = objects.single_lifecount_edh_btn6;

    cmd_btn_label[0] = objects.single_lifecount_edh_btn1_label;
    cmd_btn_label[1] = objects.single_lifecount_edh_btn2_label;
    cmd_btn_label[2] = objects.single_lifecount_edh_btn3_label;
    cmd_btn_label[3] = objects.single_lifecount_edh_btn4_label;
    cmd_btn_label[4] = objects.single_lifecount_edh_btn5_label;
    cmd_btn_label[5] = objects.single_lifecount_edh_btn6_label;

    /* Default to a 4‑player pod on load */
    layout_commander_buttons(4);
}
